### ISSUE TITLE
Automated action that runs the Linters and Checks the format

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#10]
We need an automated action that tests the formatting and linting of commits and also pull requests.

- [ ] Frontend Format Check
- [ ] Frontend Linting Check
- [ ] Backend Format Check
- [ ] Backend Linting Check

**Comment by nikkischnelle** [comment]
Frontend Pipeline is set up as mentioned in #12

**Comment by nikkischnelle** [comment]
All Actions set up
