### ISSUE TITLE
Usermanagement & routerstuff v2

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#100]
As described in #87 we want to slightly rework the user management to only allowing a user to be logged in / a player to be selected on certain pages. To achieve this, we want to wrap the RouterProvider in a custom component, that checks on every navigation, if the target page needs a user and there is none selected. If yes -> route to player-selection.
Also handle logout / player "deselect" in here when going to a page where no user should be logged in.

**Comment by Straczi** [comment]
I am actually not entirely sure if your latest commit actually fixed the potential race condition @0815Sailsman .
You are using state to set the blocked prop on the requireXXXX component, so it is also (just like the user) set async.
