### ISSUE TITLE
Housekeeping: FIGMA

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#104]
As a frontend developer

I want to have an up to date design document

Because it makes planning, communicating and actually developing the frontend easier.

NOTES:
- This is a repeating housekeeper task. 

Acceptance Criteria:
- [ ] There are no major deviations between the design document and the actual frontend.

**Comment by 0815Sailsman** [comment]
awaiting review from @Straczi

**Comment by Straczi** [comment]
Looks good to me, can't spot any significant differences between the current product and the figma demos :)
