### ISSUE TITLE
Add v1 API Endpoint to get the submitted code of a player

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#114]
As player

I want to get the code that I currently have submitted in the lobby to more easily edit it

Notes:
 - See apiv1.md for a description of the endpoint

Acceptance Criteria:
- [ ] The API v1 player code retrieval endpoint is implemented according to spec and available at /api/v1/...
- [ ] The code is fully tested or a good explanation given why it should not or cannot be tested

**Comment by 0815Sailsman** [comment]
please separate apiv0 and apiv1 in different controllers, including their tests
