### ISSUE TITLE
load urls from environment in frontend

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#127]
As a frontend dev

I want my url to get dynamically sourced from the environment

Because its an easy way to securely specifiy your urls, without revealing any information to the public while also being able to switch between urls for local development and different stages with ease.

NOTES:
- Maybe you can introduce some kind of urlProvider-service?

Acceptance Criteria:
- [ ] Urls get loaded from environment variables
- [ ] The code is fully tested or a good explanation given why it should not or cannot be tested

**Comment by 0815Sailsman** [comment]
awaiting review from @Straczi

**Comment by Straczi** [comment]
Already addressed this issue in the comments for the commit https://github.com/corewar-teamprojekt/corewar/commit/fa702a4da573a1753221863826071e24596c821d#diff-de3f076909b4639b6c9005821614ad15fd4bba0ca675c9456d70517e855f7090 . We now have three different files where api requests are made: two component files and one RestService . Please address this issue in the comments for the other commit. Everything else looks good to me:)
