### ISSUE TITLE
Bug Ticket template

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#129]
As contributor to this project

I want a default bugticket

Because I don't want to have to recreate the format by hand every time and tend to forget stuff if I don't copy paste.

NOTES:
- Check [this issue](https://github.com/corewar-teamprojekt/corewar/issues/128) for a sample

Acceptance Criteria:
- [ ] Template exists and is usable when creating new issues

**Comment by nikkischnelle** [comment]
please review @0815Sailsman

**Comment by 0815Sailsman** [comment]
lgtm, ty
