### ISSUE TITLE
Explore vscode browser integration

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#150]
As a player of the game

I want a rich and rounded experience developing the game

NOTES:
- Only **explore** how complex an integration / plugin would be, don't actually write an entire plugin etc.

Acceptance Criteria:
- [ ] Find out how complex an integration of vscode in the browser would be
- [ ] Learn about plugin development and how complicated developing a language support plugin for redcode would be

**Comment by Straczi** [comment]
will discuss findings in daily :3
