### ISSUE TITLE
Write full userflow e2e test

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#151]
As the team

we want to ensure we keep our basic userflow intact when modifying something in the codebase

Because it enables us to develop with more confidence and we hope to prevent unnecessary bugs with it.

Acceptance Criteria:
- [x] E2E test case exists, that simulates an entire game.

**Comment by 0815Sailsman** [comment]
There seem to be a few issues with running these in the pipeline. Takeover from @nikkischnelle ?

**Comment by nikkischnelle** [comment]
of course! I've already looked at this and have actually tested some things
