### ISSUE TITLE
[Bug] Uploaded Files aren't checked for encoding or type

### ISSUE THREAD

**Issue by nikkischnelle** [corewar-teamprojekt/corewar#154]
Current behavior and impact:
When users upload files, they aren't checked for type or content.
This might also be an "issue" with the text input not being validated.

Steps to reproduce:
1. Generate a file with random content (e.g. with `dd if=/dev/urandom of=largefile.txt bs=100K count=1`)
2. Upload said file in the user code upload menu
Alternatively:
1. Upload a binary from `/usr/bin` in the user code upload menu

Expected behavior:
Text box stays empty, when a file, that isn't a text-file is uploaded.

Acceptance Criteria:
- [ ] Code Text box stays empty, when a file, that isn't a text-file is uploaded.

**Comment by Straczi** [comment]
Same here as in #155 : Since we are currently working on using a real code editor and therefore (probably) redo the entire coding page, i will would look at this issue when doing that.
