### ISSUE TITLE
[Bug] File size restrictions for code upload does not show error 

### ISSUE THREAD

**Issue by nikkischnelle** [corewar-teamprojekt/corewar#155]
Current behavior and impact:
When users try to upload files, that are too big, nginx inside our container images currently returns a `413 Request Entity Too Large`. The Frontend still goes on to waiting-for-opponent. 

Steps to reproduce:
1. Upload a file too large for nginx (e.g. 1M with `dd if=/dev/urandom of=largefile.txt bs=100M count=1`)

Expected behavior:
Frontend reports error back to user and does not advance to the next page in userflow, as no code was actually uploaded.

Acceptance Criteria:
- [ ] Frontend shows formatted error message for 413 and generally checks error codes on code upload.

**Comment by Straczi** [comment]
1. that kida surprises me, since we actually check if the request was succesful before advancing to the next page.
2.  Since we are currently working on using a real code editor and therefore (probably) redo the entire coding page, i will would look at this issue when doing that.

**Comment by 0815Sailsman** [comment]
@Straczi implemented a failsafe that should cover this on #209 , but we don't see the 413 response code in the deployments. Can you double check that @nikkischnelle ?

**Comment by nikkischnelle** [comment]
My best theory is CORS, because... well it's CORS and a pain in the backside xD
Will have to try this out a lot i guess

**Comment by Straczi** [comment]
> My best theory is CORS, because... well it's CORS and a pain in the backside xD
> Will have to try this out a lot i guess

![rapidsave.com_jgh976mqqzzd1.gif](https://github.com/user-attachments/assets/3273e538-7b62-4580-aaf4-ae7c0c3bab2c)
