### ISSUE TITLE
[Bug] Shork Settings don't respect defaultInstruction

### ISSUE THREAD

**Issue by nikkischnelle** [corewar-teamprojekt/corewar#157]
Current behavior and impact:
The shork's settings do not respect the defaultInstruction

Steps to reproduce:
1. Create Settings with some default instruction
2. Convert Settings to InternalSettings
3. Observe the default instruction in the internal settings

Expected behavior:
The default instruction string in Settings is parsed and converted to an instruction in InternalSettings.
If the default instruction string can't be parsed, the conversion to internal settings fails. 

Acceptance Criteria:
- [ ] The default instruction string in Settings is parsed and converted to an instruction in InternalSettings.
- [ ] If the default instruction string can't be parsed, the conversion to internal settings fails.

**Comment by nikkischnelle** [comment]
![image](https://github.com/user-attachments/assets/0c2140fc-16a7-4e35-b671-ed2be0188720)

**Comment by flamion** [comment]
Fixing this requires that we plan/organize a method of returning errors to the callers as the conversion of the source code of an instruction is a fallible operation

**Comment by flamion** [comment]
This is now unblocked, we now have the possibility of returning more than just a string from the run method.
The GameResult could be wrapped in a Kotlin result and return some kind of error Object with the compilation error or something.
This is left up to discussion / the implementer
