### ISSUE TITLE
Implement (mocked) /status

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#18]
The /status endpoint has to be implemented according to spec.
As the interpreter is not yet available, the Mock interpreter has to be used

**Comment by nikkischnelle** [comment]
I started work on this today in the `18-19-20_MockShark` branch.
Still missing is:

- [ ] Testing

**Comment by flamion** [comment]
Why has this been closed? The branch still exists and I couldn't find a merged PR for it
