### ISSUE TITLE
Create result display page v1

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#28]
[Design](https://www.figma.com/design/hUqMfggYePIv4Qjb0rFMVC/corewar?node-id=103-1568&t=E1u8M8TZKFvd9zyI-4)

Same thing as in #27  page, use atomic compnents and only test stuff like routing and user changing in here.

Depends on #21 #25 #24 #48 #49

**Comment by nikkischnelle** [comment]
@0815Sailsman Kilian says this is implemented and should be closed
