### ISSUE TITLE
[BUG] lobbystatus responds with UNDECIDED instead of DRAW

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#290]
Current behavior and impact:
lobby status disrespects the spec and returns `UNDECIDED` instead of `DRAW` for a draw.

Steps to reproduce:
1. Check the implementation, or
2. Create a lobby with a game that ends in a draw
3. Check the response

Expected behavior:
API uses `DRAW` instead of `UNDECIDED`

Acceptance Criteria:
- [ ] Endpoint conforms to spec

**Comment by Straczi** [comment]
(lobbStatus endpoint :( )
