### ISSUE TITLE
Resolved addresses with maxRead/maxWrite distance are not centered around the current address

### ISSUE THREAD

**Issue by PietHelzel** [corewar-teamprojekt/corewar#303]
Current behavior and impact:
- When reading or writing from memory outside of the maxRead/maxWrite distance, the address is calculated as currentAddress + (offset % maxDistance). This is not spec-compliant, however.

Steps to reproduce:
1. Read or write at a greater offset than the respective maxDistance.

Expected behavior:
- Read and write operations are "centered" around the current instruction. The range is [sourceAddress - maxDistance/2; sourceAddress + maxDistance/2].

Acceptance Criteria:
- [ ] The functionality is implemented according to spec

**Comment by nikkischnelle** [comment]
![oh no](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia4.giphy.com%2Fmedia%2FWpaVhEcp3Qo2TjwyI1%2Fgiphy.gif&f=1&nofb=1&ipt=e24bc0c145edf8ab128155da8daf37c7b0cdceb7de015a4198e5d335763547b6&ipo=images)

**Comment by PietHelzel** [comment]
Fixed by #325
