### ISSUE TITLE
Lobby Status responds with 400 for a missing lobby

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#307]
Current behavior and impact:
Lobby Status responds with a 400 when the specified lobby ID does not exist.
This does not seem right, a 404 would more fitting imo.
The spec does not specify at all what should happen for a not existing lobby ID.

Steps to reproduce:
1. Ask the API for the status of a nonexistant lobby(id)
2. API responds with `400: No lobby with that id`

Expected behavior:
HTTP 404

Acceptance Criteria:
- [x] Spec has been updated
- [x] Implementation has been updated

**Comment by nikkischnelle** [comment]
spec has been updated. @TR1NITROTOLUOL @steinerthelion does one of you want to take over?

**Comment by TR1NITROTOLUOL** [comment]
> spec has been updated. [@TR1NITROTOLUOL](https://github.com/TR1NITROTOLUOL) [@steinerthelion](https://github.com/steinerthelion) does one of you want to take over?

Yes, I would take over. I'll assign it myself.
