### ISSUE TITLE
Add common program examples to code input page

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#340]
As a first time player of the game

I want to be able to choose from a few basic programs

Because it enables me to check out the capabilities of the application without having to learn redcode.

NOTES:
- Maybe add Imp, Dwarf and some third program.
- Design the example program selection similar to the challenges found on https://bitshift.flamion.dev/

Dwarf:
```
add.ab  #4, 3
mov.i   2, @2
jmp     -2
dat     #0, #0
```

Mice:
```
mov.ab  #12, -1
mov.i   @-2, <5
djn     -1, -3
spl     @3, 0
add.ab  #653, 2
jmz     -5, -6
dat     #0, #833
```

Scanner:
```
add    #10, 1
jmz.f  -1, 5
mov.i  2, >-1
jmp    -1
```

Acceptance Criteria:
- [ ] 3 cards exist next to the code editor
- [ ] The cards have the title of the program they represent and a short description of what the program does.
- [ ] Each card has a button at the bottom, that opens a toast, asking the user if they want to select this program, overriding their current program.
- [ ] Pressing Ok in the toast, replaces the current program with the selected program.
- [ ] The code is fully tested or a good explanation given why it should not or cannot be tested

**Comment by Straczi** [comment]
Already branching from 294-game-visualization-page, since that PR is almost approved :+1:
