### ISSUE TITLE
Fix backend pre-commit hook

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#41]
The pre-commit hook for format checking the backend is broken. It assumes there is a gradlew in the interpreter and api folder, but none exists. 
The workspace gradlew must be used instead

**Comment by nikkischnelle** [comment]
Can't test right now, but should be fixed. Feedback would be appreciated @flamion

**Comment by flamion** [comment]
Hooks seem to work again, but the regex could be extended. That is out of the scope for this story though.
