### ISSUE TITLE
Explain the makeup of a redcode instruction in the wiki

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#42]
We need a detailed explanation / spec of the makeup of a redcode instruction.
The Redcode address modes and modifiers should be explained with enough detail to enable implementors to basically only reference the wiki.
NOTE:
The explanations / spec of all of the instructions themselves are not part of this story.

Completion criteria:

- [x] The Redcode address modes have been explained in the wiki
- [x] The Redcode modifiers have been explained in the wiki
- [x] Examples have been given, if applicable

**Comment by PietHelzel** [comment]
@flamion Take a look please
