### ISSUE TITLE
Adjust pre-commit hook regex

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#46]
As Developer

I want to write clean commit messages. Currently the regex for the commit messages only allows you to write the issues like this: `[#31,#32,#33]`. The regex should be adjusted to also allow spaces **after** the comma, like this: `[#31, #32, #33]`.

Because it makes the development experience nicer

Acceptance Criteria:
- [ ] The pre-commit hook allows a single space after the comma between issue reference numbers

**Comment by nikkischnelle** [comment]
As this is a matter of taste, I think we should get more opinions in before changing the regex. Because my opinion is: the current way looks cleaner, and we should only allow one of the options for consistency. 
What does @0815Sailsman think?

**Comment by flamion** [comment]
Answer from @0815Sailsman, we should allow both but modify the acceptance criteria to allow only a single space

**Comment by nikkischnelle** [comment]
I personally think it's ugly, but it's done
