### ISSUE TITLE
Pre-Commit hook rejects valid commits

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#47]
As Developer

I would like the kotlin linter/formatter to only run on staged files for the pre-commit hook check

So that I can make small commits, as currently a single unfinished/not compiling file that is not contained in the commit is enough that the formatter rejects the commit.

Lowest Priority, this is almost a non issue

Notes:
- This does not have a milestone on purpose. This is not a blocker and also not annoying enough to warrant investing a ton of time into.

Acceptance Criteria:
- [ ] Pre-Commit hook only checks the staged files and doesn't reject commits containing only valid code

**Comment by nikkischnelle** [comment]
Solved by using https://github.com/nikkischnelle/ktfmt-pre-commit-hook
