### ISSUE TITLE
Check out (and fix) code scanning alert - Fast refresh only works when a file only exports components

### ISSUE THREAD

**Issue by nikkischnelle** [corewar-teamprojekt/corewar#51]
Code scanning found an issue with code you pushed, @Straczi 
The pre-commit hooks might prevent pushing changes to the file right now, so it's important to sort this warning out.

Tracking issue for:
- [ ] https://github.com/corewar-teamprojekt/corewar/security/code-scanning/1

**Comment by Straczi** [comment]
problems were fixed

**Comment by 0815Sailsman** [comment]
Not it hasn't been, different location. Look into ThemeProvier.tsx
