### ISSUE TITLE
Pre-Commit lint regex is broken

### ISSUE THREAD

**Issue by flamion** [corewar-teamprojekt/corewar#72]
As developer

I want clean commit messages

As it makes development easier and nicer

Currently the pre-commit lint regex is broken and accepts commit messages such as
- `#42 implement foo to wrangle bar dingler`

Acceptance Criteria:
- [ ] pre-commit lint regex ensures only commit messages that adhere to the agreed upon format are allowed

**Comment by nikkischnelle** [comment]
The commitlint project didn't work for us, so I wrote a python script that lints commits instead. It might still not be bulletproof, but I included some unit tests to cover the cases that came to mind.
