### ISSUE TITLE
Implement result display page v2

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#89]
As a player

I want to see a detailed summary of my past game

Because I like nerdy numbers, why else would I play this game 💀 

NOTES:
- [Design](https://www.figma.com/design/hUqMfggYePIv4Qjb0rFMVC/corewar?node-id=193-4581&t=hkzwQhcjylwq1lUj-4)
- Statically Mock unavailable api ressources

Acceptance Criteria:
- [ ] Displays past game stats
- [ ] The code is fully tested or a good explanation given why it should not or cannot be tested

**Comment by Straczi** [comment]
branch already exists and some work has been done
