### ISSUE TITLE
Introduce waiting for opponent page

### ISSUE THREAD

**Issue by 0815Sailsman** [corewar-teamprojekt/corewar#90]
As a player

I want to see, that I am waiting for my opponent

Because just waiting might not be verbose enough. It might lead me to think that the game is doing cringe stuff, when in reality it is their opponent!

NOTES:
- Blocked by changing user handling in #87 
- [Design](https://www.figma.com/design/hUqMfggYePIv4Qjb0rFMVC/corewar?node-id=198-211&t=hkzwQhcjylwq1lUj-4)

Acceptance Criteria:
- [ ] Polls status until game started
- [ ] Routes to waiting for result after game start
- [ ] The code is fully tested or a good explanation given why it should not or cannot be tested

**Comment by 0815Sailsman** [comment]
I consciously evaded introducing an abstraction for a common, abstracted loading page, since I think, that the benefit would not be worth it. We will be re-designing these pages very soon anyways, and I personally don't have a problem with the code duplication in them.

In short: I think refactoring to an abstract loading page would not be worth it.

**Comment by 0815Sailsman** [comment]
Awaiting review from @Straczi

**Comment by Straczi** [comment]
Added some comments : https://github.com/corewar-teamprojekt/corewar/commit/fa702a4da573a1753221863826071e24596c821d#diff-de3f076909b4639b6c9005821614ad15fd4bba0ca675c9456d70517e855f7090

**Comment by 0815Sailsman** [comment]
Fixed everything, except for the shared logic inbetween the two waiting pages. I don't think we should be that trigger happy with introducing abstractions left and right, and to me its absolutely fine having those two co-exist here for now.

**Comment by Straczi** [comment]
> Fixed everything, except for the shared logic inbetween the two waiting pages. I don't think we should be that trigger happy with introducing abstractions left and right, and to me its absolutely fine having those two co-exist here for now.

After finishing the mvp, it would (in my opinion) also be cleaner if we switched from polling to websocket communication, so i have no problem leaving  it as it is (for now). But IF we should continue to do polling and maybe use it in even more components, we should consider building something for it, instead of copying code everywhere.

Everything looks good:)  :+1:
